# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI Full Tests Node.js

on:
  workflow_dispatch:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    timeout-minutes: 10
    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install deps
      run: npm ci

    - name: Build package
      run: npm run build --if-present

    - name: Run tests
      run: npm run test
      continue-on-error: true

    - name: Upload report
      uses: actions/upload-artifact@v3
      with: 
        name: test-report
        if-no-files-found: error
        path: ./jest-html-reports

    - name: Run tests coverage
      run: npm run test:coverage
      continue-on-error: true

    - name: Upload coverage
      uses: actions/upload-artifact@v3
      with:
        name: coverage
        if-no-files-found: error
        path: ./coverage

      #5801403357:AAGmdEXSJltDNWBTvtKRTqLz2y9u7FURuxs

    - name: send telegram message on push
      uses: appleboy/telegram-action@master
      with:
        to: -1002114535023
        token: 5801403357:AAGmdEXSJltDNWBTvtKRTqLz2y9u7FURuxs
        photo: ./paw.jpg
        format: ./jest-html-reports/test-report.html
        message: |
          hello, it's test

